### ISSUE TITLE
Exception after VNC Connection

### ISSUE THREAD

**Issue by pwigger** [Lernstick2-Team/rscc#15]
Jun 29, 2017 11:19:59 PM ch.imedias.rsccfx.model.Rscc sshSessionHandler
INFORMATION: Sent Key to Keyserver
com.jcraft.jsch.JSchException: PortForwardingL: local port 127.0.0.1:5900 is not registered.
	at com.jcraft.jsch.PortWatcher.delPort(PortWatcher.java:118)
	at com.jcraft.jsch.Session.delPortForwardingL(Session.java:1865)
	at ch.imedias.rsccfx.model.Rscc.sshTunnelPortForwarding(Rscc.java:538)
	at ch.imedias.rsccfx.model.Rscc.killConnection(Rscc.java:434)
	at ch.imedias.rsccfx.model.Rscc.refreshKey(Rscc.java:771)
	at ch.imedias.rsccfx.view.RsccRequestPresenter.lambda$attachEvents$5(RsccRequestPresenter.java:127)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at ch.imedias.rsccfx.model.Rscc.setVncSessionRunning(Rscc.java:1001)
	at ch.imedias.rsccfx.model.VncServerHandler$2.run(VncServerHandler.java:149)

**Comment by rmosimann** [comment]
this is already covered, in actual branch, see #14
